name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set zip filename
        run: echo "zip_filename=vrm_rigify_for_unity-${{ github.ref_name }}.zip" >> $GITHUB_ENV

      - name: Copy LICENSE and NOTICE files
        run: |
          cp -p LICENSE vrm_rigify_for_unity/
          cp -p NOTICE vrm_rigify_for_unity/

      - name: Create zip file
        run: |
          zip -r "${{ env.zip_filename }}" vrm_rigify_for_unity -x "vrm_rigify_for_unity/__pycache__/*" "vrm_rigify_for_unity/**/__pycache__/*"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ env.zip_filename }}
          draft: true
          generate_release_notes: true
          prerelease: false